[package]
name = "potatocho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rfd = "0.11.2"

[profile.dev]
overflow-checks = false